"""
Generated documentation:

* ``docs/data.md``: data dictionary and provenance, from the manifest;
* the results table in ``README.md`` (between the RESULTS markers), from ``evaluation.json``, so no score in the
  README is ever typed by hand.
"""

from __future__ import annotations

import json

from src.common import manifest
from src.common.config import Config, load_config

HEADER = """# Data: provenance and data dictionary

_Generated by `python -m src.pipeline.run --only docs` from `data/<district>/manifest.json`.
Do not edit by hand._

Every dataset below was produced by the named module from the named public source. Raw rasters
and downloads (`data/<district>/raw/`, `data/_shared/`) are git-ignored and are re-created by the
pipeline. Each entry has its SHA-256, so any later change to a file is detectable.

## What is observed, what is modelled, what is simulated

| Role | Dataset | Nature |
|---|---|---|
| Model input (X) | ECMWF IFS 0.25° forecasts, lead 1-5 days, area-averaged to blocks | **real archived NWP forecasts** |
| Rain truth (y) | CHIRPS v2.0 daily 0.05°, area-averaged to GPs | observation-based (satellite + gauges) |
| T / RH truth (y) | ERA5-Land 0.1° | reanalysis (observation-constrained model) |
| Wind truth (y) | ERA5 0.25° | reanalysis, coarser than a GP (documented limitation) |
| Independent check | IMD 0.25° gauge-gridded rainfall | gauge observations, never used in training |
| Static covariates | Copernicus DEM 30 m, ESA WorldCover 10 m, HydroRIVERS, SoilGrids, CHPclim, MODIS NDVI | observations / products |
| Simulated | **nothing**. The former synthetic forecast, orographic "ground truth" and formula-based DEM were removed. | - |

"""


def build(cfg: Config | None = None) -> str:
    cfg = cfg or load_config()
    m = manifest.load(cfg.paths.data / "manifest.json")
    lines = [HEADER, f"## District: {cfg.district_name} (`data/{cfg.key}/`)\n",
             "| Dataset | File | Source | Licence | Produced by | Generated (UTC) | Size | SHA-256 |",
             "|---|---|---|---|---|---|---|---|"]
    for name, e in sorted(m.items()):
        size = f"{e['bytes'] / 1e6:.2f} MB" if e.get("bytes") else "-"
        sha = (e.get("sha256") or "-")[:12]
        lines.append(f"| {name} | `{e['path']}` | {e['source']} | {e['licence']} | `{e['produced_by']}` | "
                     f"{e['generated_utc']} | {size} | `{sha}` |")
    qa = cfg.paths.reports / "boundary_qa.json"
    if qa.exists():
        q = json.loads(qa.read_text(encoding="utf-8"))
        lines += ["", "## Boundary QA", "",
                  f"* raw LGD polygons: {q['raw_polygons']}; non-GP polygons (no `gp_code`, urban/forest): "
                  f"{q['non_gp_polygons']} ({q['non_gp_area_km2']} km²)",
                  f"* multi-part GPs dissolved: {q['multipart_gp_codes']}; Gram Panchayats: {q['gram_panchayats']} "
                  f"(modelled {q['modelled_gram_panchayats']})",
                  f"* GP -> block by largest overlap; disagreements with the LGD attribute: {q['attribute_disagreements']}",
                  "* QA map: `outputs/<district>/reports/boundary_qa_map.png`"]
    ds = cfg.paths.reports / "dataset_summary.json"
    if ds.exists():
        lines += ["", "## Modelling table", "", "```json", ds.read_text(encoding="utf-8"), "```"]
    text = "\n".join(lines) + "\n"
    (cfg.paths.root / "docs" / "data.md").write_text(text, encoding="utf-8")
    fill_readme_results(cfg)
    return text


START, END = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"
NAMES = {"rain": "Rainfall", "tmax": "Max temperature", "tmin": "Min temperature", "rh": "Humidity", "wind": "Wind"}


def _pct(x: float) -> str:
    return f"{100 * x:+.1f}%"


def fill_readme_results(cfg: Config) -> str:
    ev = json.loads((cfg.paths.reports / "evaluation.json").read_text(encoding="utf-8"))
    h = ev["headline"]
    pp, fm = h["perfect_prognosis"], h["per_variable"]
    rows = ["| Variable | Disaggregation (observed block in) | Forecast mode (ECMWF block in) | "
            "Forecast-mode error: panchayat vs block copy |", "|---|---|---|---|"]
    for v, name in NAMES.items():
        if v not in fm:
            continue
        d, p = fm[v], pp.get(v)
        dis = f"{_pct(p['skill_vs_block_copy'])} (CI {_pct(p['ci'][0])} to {_pct(p['ci'][1])})" if p else "-"
        rows.append(f"| {name} | {dis} | {_pct(d['skill_vs_block_copy'])} (CI {_pct(d['ci'][0])} to "
                    f"{_pct(d['ci'][1])}) | {d['rmse_model']:.2f} vs {d['rmse_block_copy']:.2f} |")
    period = f"{cfg['validation']['test_start']} to {cfg['period']['end']}"
    table = "\n".join([f"Skill = RMSE reduction vs copying the block value; test period {period}; "
                        f"lead days {cfg.lead_days[0]}-{cfg.lead_days[-1]}.", "", *rows])
    readme = cfg.paths.root / "README.md"
    txt = readme.read_text(encoding="utf-8")
    i, j = txt.index(START) + len(START), txt.index(END)
    readme.write_text(txt[:i] + "\n" + table + "\n" + txt[j:], encoding="utf-8")
    return table


if __name__ == "__main__":
    build()
