"""Generate ``data/README.md`` (data dictionary and provenance) from the manifest (audit 3.9)."""

from __future__ import annotations

import json

from src.common import manifest
from src.common.config import Config, load_config

HEADER = """# Data directory: provenance and data dictionary

_Generated by `python -m src.pipeline.run --only docs` from `data/<district>/manifest.json`.
Do not edit by hand._

Every dataset below was produced by the named module from the named public source. Raw rasters
and downloads (`data/<district>/raw/`, `data/_shared/`) are git-ignored and are re-created by the
pipeline. Each entry has its SHA-256, so any later change to a file is detectable.

## What is observed, what is modelled, what is simulated

| Role | Dataset | Nature |
|---|---|---|
| Model input (X) | ECMWF IFS 0.25° forecasts, lead 1-5 days, area-averaged to blocks | **real archived NWP forecasts** |
| Rain truth (y) | CHIRPS v2.0 daily 0.05°, area-averaged to GPs | observation-based (satellite + gauges) |
| T / RH truth (y) | ERA5-Land 0.1° | reanalysis (observation-constrained model) |
| Wind truth (y) | ERA5 0.25° | reanalysis, coarser than a GP (documented limitation) |
| Independent check | IMD 0.25° gauge-gridded rainfall | gauge observations, never used in training |
| Static covariates | Copernicus DEM 30 m, ESA WorldCover 10 m, HydroRIVERS, SoilGrids, CHPclim, MODIS NDVI | observations / products |
| Simulated | **nothing**. The former synthetic forecast, orographic "ground truth" and formula-based DEM were removed. | - |

"""


def build(cfg: Config | None = None) -> str:
    cfg = cfg or load_config()
    m = manifest.load(cfg.paths.data / "manifest.json")
    lines = [HEADER, f"## District: {cfg.district_name} (`data/{cfg.key}/`)\n",
             "| Dataset | File | Source | Licence | Produced by | Generated (UTC) | Size | SHA-256 |",
             "|---|---|---|---|---|---|---|---|"]
    for name, e in sorted(m.items()):
        size = f"{e['bytes'] / 1e6:.2f} MB" if e.get("bytes") else "-"
        sha = (e.get("sha256") or "-")[:12]
        lines.append(f"| {name} | `{e['path']}` | {e['source']} | {e['licence']} | `{e['produced_by']}` | "
                     f"{e['generated_utc']} | {size} | `{sha}` |")
    qa = cfg.paths.reports / "boundary_qa.json"
    if qa.exists():
        q = json.loads(qa.read_text(encoding="utf-8"))
        lines += ["", "## Boundary QA", "",
                  f"* raw LGD polygons: {q['raw_polygons']}; non-GP polygons (no `gp_code`, urban/forest): "
                  f"{q['non_gp_polygons']} ({q['non_gp_area_km2']} km²)",
                  f"* multi-part GPs dissolved: {q['multipart_gp_codes']}; Gram Panchayats: {q['gram_panchayats']} "
                  f"(modelled {q['modelled_gram_panchayats']})",
                  f"* GP -> block by largest overlap; disagreements with the LGD attribute: {q['attribute_disagreements']}",
                  "* QA map: `outputs/<district>/reports/boundary_qa_map.png`"]
    ds = cfg.paths.reports / "dataset_summary.json"
    if ds.exists():
        lines += ["", "## Modelling table", "", "```json", ds.read_text(encoding="utf-8"), "```"]
    text = "\n".join(lines) + "\n"
    (cfg.paths.root / "data" / "README.md").write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    build()
